### PR TITLE
Improve the quickstart

### PR DESCRIPTION
**Pull request by jasonLaster**
This makes several readability improvements

1. Moves Inspect replay to it own page
2. Consolidates view and inspect replay into one section
3. Makes the replay links a real link
4. Moves record with playwright + cypress up

### CODE REVIEW

**Comment by crutchcorn** [comment]
I worry about the discoverability of the `Inspect` page. Let's add a "next page" or "next steps" button to go above the FAQ

I also noticed this issue with the link inside of the "terminal":

image

Once these are fixed, I think this is a good change and we should merge

**Review by crutchcorn — CHANGES_REQUESTED** [review]
Requesting changes per last comment

**Comment by jasonLaster** [comment]
Thanks. Addressed these two changes and landing. By the way, the read more links and descriptions were pretty weak before.

**Comment by bvaughn** [comment]
RE landing: Seems like this breaks e2e tests?

I can't view the failed recording because I don't have access to this team/workspace though.

**Pull request merged**
